#!/bin/bash -l
#SBATCH -N 2
#SBATCH -C knl
#SBATCH -p debug
#SBATCH -t 00:10:00
#SBATCH -J job-ray
#SBATCH -o job-ray.o%j
#SBATCH -e job-ray.e%j

#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=68

conda activate nums

# Getting the node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)


# Start head node.
port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "Starting HEAD at $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --block &

sleep 10


# Start workers.
worker_num=$((SLURM_JOB_NUM_NODES - 1))

for ((i = 1; i <= worker_num; i++)); do
    node_i=${nodes_array[$i]}
    echo "Starting WORKER $i at $node_i"
    srun --nodes=1 --ntasks=1 -w "$node_i" \
        ray start --address "$ip_head" \
        --num-cpus "${SLURM_CPUS_PER_TASK}" --block &
    sleep 5
done


export MKL_NUM_THREADS=1
python -u ./time_sparse.py --address $ip_head --cluster-shape 1,1
