name: 🚀 Feature request
description: Suggest an idea for a NumS feature
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: >
        This should be a clear and concise description of what you want to happen.

  - type: textarea
    attributes:
      label: Use case
      description: >
        Describe the use case for your proposed feature. It'll help us understand and
        prioritize the feature request.
      placeholder: >
        Rather than telling us how you might implement this feature, try to take a
        step back and describe what you are trying to achieve.
