name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Build NumS
        run: |
          python -m pip install build
          python -m build
      - name: Upload distribution archives
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m pip install twine
          python -m twine upload --repository testpypi dist/*
